### PR TITLE
replace musicify with my updated fork

### PR DESCRIPTION
**Pull request by OmriOn**
musicify hasnt added a song in over 2 years, so replace it with my updated fork that i do add to actively.

### CODE REVIEW

**Comment by Erb3** [comment]
ping: @EmmaKnijn @knijn

**Comment by EmmaKnijn** [comment]
Replacing the entire repo won't update the music, you'll need to replace musicify-songs, I'll update it in the source

**Comment by OmriOn** [comment]
> Replacing the entire repo won't update the music, you'll need to replace musicify-songs, I'll update it in the source

i did replace musicify-songs, i just made a repo with all links being replaced to point to my musicify-songs

**Comment by EmmaKnijn** [comment]
I'll change my repo, gimme ~10m

**Comment by OmriOn** [comment]
ok ill close th9is then

**Pull request closed without merging**
